console.group("Group 1");
console.log("Message One");
console.log("Message Tow");
console.group("Child Group");
console.log("Message One");
console.log("Message Tow");
console.group("Grand Child Group");
console.log("Message One");
console.log("Message Tow");
console.groupEnd();
console.groupEnd();
console.group("Group 2");